name: chronos
description: Chronos — ежедневное фото и воспоминания
publish_to: none
version: 0.25.0+25

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.0
  flutter_timezone: ^4.1.0
  timezone: ^0.10.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/launcher/
