name: chronos
description: Chronos — ежедневное фото и воспоминания
publish_to: none
version: 0.9.0+26

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.0
  flutter_timezone: ^4.1.0
  timezone: ^0.10.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  exif: ^3.3.0
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  geocoding: ^3.0.0
  record: ^5.2.0
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
