name: chronos
description: Chronos — ежедневное фото и воспоминания
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.0
  flutter_timezone: ^4.1.0
  timezone: ^0.10.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
